a=int(input('enter the number'))
b=int (input('enter the number'))
print(a+b)
a=int(input('enter the number'))
b=int (input('enter the number'))
print(a-b)
a=int(input('enter the number'))
b=int (input('enter the number'))
print(a/b)
a=float(input('enter the number'))
b=float(input('enter the number'))
print(a%b)
a=int(input('enter the number'))
b=int(input('enter the number'))
print(a*b)
